//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _EDD_Proyecto1_Cliente.ServidorIPEstatica {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorIPEstatica.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.HelloWorldResponse HelloWorld(_EDD_Proyecto1_Cliente.ServidorIPEstatica.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarUsuario", ReplyAction="*")]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarUsuarioResponse insertarUsuario(_EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name graficarUsuariosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/graficarUsuarios", ReplyAction="*")]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarUsuariosResponse graficarUsuarios(_EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarUsuariosRequest request);
        
        // CODEGEN: Generating message contract since element name graficarEspejoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/graficarEspejo", ReplyAction="*")]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarEspejoResponse graficarEspejo(_EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarEspejoRequest request);
        
        // CODEGEN: Generating message contract since element name obtenerAlturaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerAltura", ReplyAction="*")]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerAlturaResponse obtenerAltura(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerAlturaRequest request);
        
        // CODEGEN: Generating message contract since element name obtenerHojasResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerHojas", ReplyAction="*")]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerHojasResponse obtenerHojas(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerHojasRequest request);
        
        // CODEGEN: Generating message contract since element name obtenerRamasResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerRamas", ReplyAction="*")]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerRamasResponse obtenerRamas(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerRamasRequest request);
        
        // CODEGEN: Generating message contract since element name obtenerNivelesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerNiveles", ReplyAction="*")]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNivelesResponse obtenerNiveles(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNivelesRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarJuego", ReplyAction="*")]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarJuegoResponse insertarJuego(_EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarJuegoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/limpiar", ReplyAction="*")]
        void limpiar();
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarUsuario", ReplyAction="*")]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.eliminarUsuarioResponse eliminarUsuario(_EDD_Proyecto1_Cliente.ServidorIPEstatica.eliminarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerNickname", ReplyAction="*")]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNicknameResponse obtenerNickname(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNicknameRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerPassword", ReplyAction="*")]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerPasswordResponse obtenerPassword(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerPasswordRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCorreoElectronico", ReplyAction="*")]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerCorreoElectronicoResponse obtenerCorreoElectronico(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerCorreoElectronicoRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerConectado", ReplyAction="*")]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerConectadoResponse obtenerConectado(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerConectadoRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerJuegos", ReplyAction="*")]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerJuegosResponse obtenerJuegos(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerJuegosRequest request);
        
        // CODEGEN: Generating message contract since element name consultarJuegosGanadosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarJuegosGanados", ReplyAction="*")]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarJuegosGanadosResponse consultarJuegosGanados(_EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarJuegosGanadosRequest request);
        
        // CODEGEN: Generating message contract since element name consultarPorcentajeUnidadesDestruidasResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarPorcentajeUnidadesDestruidas", ReplyAction="*")]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarPorcentajeUnidadesDestruidasResponse consultarPorcentajeUnidadesDestruidas(_EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarPorcentajeUnidadesDestruidasRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.loginResponse login(_EDD_Proyecto1_Cliente.ServidorIPEstatica.loginRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/conectar", ReplyAction="*")]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.conectarResponse conectar(_EDD_Proyecto1_Cliente.ServidorIPEstatica.conectarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(_EDD_Proyecto1_Cliente.ServidorIPEstatica.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(_EDD_Proyecto1_Cliente.ServidorIPEstatica.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarUsuarioRequestBody Body;
        
        public insertarUsuarioRequest() {
        }
        
        public insertarUsuarioRequest(_EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contraseña;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string correoElectronico;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool conectado;
        
        public insertarUsuarioRequestBody() {
        }
        
        public insertarUsuarioRequestBody(string nickname, string contraseña, string correoElectronico, bool conectado) {
            this.nickname = nickname;
            this.contraseña = contraseña;
            this.correoElectronico = correoElectronico;
            this.conectado = conectado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarUsuarioResponseBody Body;
        
        public insertarUsuarioResponse() {
        }
        
        public insertarUsuarioResponse(_EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertarUsuarioResult;
        
        public insertarUsuarioResponseBody() {
        }
        
        public insertarUsuarioResponseBody(string insertarUsuarioResult) {
            this.insertarUsuarioResult = insertarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class graficarUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="graficarUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarUsuariosRequestBody Body;
        
        public graficarUsuariosRequest() {
        }
        
        public graficarUsuariosRequest(_EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class graficarUsuariosRequestBody {
        
        public graficarUsuariosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class graficarUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="graficarUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarUsuariosResponseBody Body;
        
        public graficarUsuariosResponse() {
        }
        
        public graficarUsuariosResponse(_EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class graficarUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string graficarUsuariosResult;
        
        public graficarUsuariosResponseBody() {
        }
        
        public graficarUsuariosResponseBody(string graficarUsuariosResult) {
            this.graficarUsuariosResult = graficarUsuariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class graficarEspejoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="graficarEspejo", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarEspejoRequestBody Body;
        
        public graficarEspejoRequest() {
        }
        
        public graficarEspejoRequest(_EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarEspejoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class graficarEspejoRequestBody {
        
        public graficarEspejoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class graficarEspejoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="graficarEspejoResponse", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarEspejoResponseBody Body;
        
        public graficarEspejoResponse() {
        }
        
        public graficarEspejoResponse(_EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarEspejoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class graficarEspejoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string graficarEspejoResult;
        
        public graficarEspejoResponseBody() {
        }
        
        public graficarEspejoResponseBody(string graficarEspejoResult) {
            this.graficarEspejoResult = graficarEspejoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerAlturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerAltura", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerAlturaRequestBody Body;
        
        public obtenerAlturaRequest() {
        }
        
        public obtenerAlturaRequest(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerAlturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class obtenerAlturaRequestBody {
        
        public obtenerAlturaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerAlturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerAlturaResponse", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerAlturaResponseBody Body;
        
        public obtenerAlturaResponse() {
        }
        
        public obtenerAlturaResponse(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerAlturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerAlturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string obtenerAlturaResult;
        
        public obtenerAlturaResponseBody() {
        }
        
        public obtenerAlturaResponseBody(string obtenerAlturaResult) {
            this.obtenerAlturaResult = obtenerAlturaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerHojasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerHojas", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerHojasRequestBody Body;
        
        public obtenerHojasRequest() {
        }
        
        public obtenerHojasRequest(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerHojasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class obtenerHojasRequestBody {
        
        public obtenerHojasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerHojasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerHojasResponse", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerHojasResponseBody Body;
        
        public obtenerHojasResponse() {
        }
        
        public obtenerHojasResponse(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerHojasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerHojasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string obtenerHojasResult;
        
        public obtenerHojasResponseBody() {
        }
        
        public obtenerHojasResponseBody(string obtenerHojasResult) {
            this.obtenerHojasResult = obtenerHojasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerRamasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerRamas", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerRamasRequestBody Body;
        
        public obtenerRamasRequest() {
        }
        
        public obtenerRamasRequest(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerRamasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class obtenerRamasRequestBody {
        
        public obtenerRamasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerRamasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerRamasResponse", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerRamasResponseBody Body;
        
        public obtenerRamasResponse() {
        }
        
        public obtenerRamasResponse(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerRamasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerRamasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string obtenerRamasResult;
        
        public obtenerRamasResponseBody() {
        }
        
        public obtenerRamasResponseBody(string obtenerRamasResult) {
            this.obtenerRamasResult = obtenerRamasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerNivelesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerNiveles", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNivelesRequestBody Body;
        
        public obtenerNivelesRequest() {
        }
        
        public obtenerNivelesRequest(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNivelesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class obtenerNivelesRequestBody {
        
        public obtenerNivelesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerNivelesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerNivelesResponse", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNivelesResponseBody Body;
        
        public obtenerNivelesResponse() {
        }
        
        public obtenerNivelesResponse(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNivelesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerNivelesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string obtenerNivelesResult;
        
        public obtenerNivelesResponseBody() {
        }
        
        public obtenerNivelesResponseBody(string obtenerNivelesResult) {
            this.obtenerNivelesResult = obtenerNivelesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarJuegoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarJuego", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarJuegoRequestBody Body;
        
        public insertarJuegoRequest() {
        }
        
        public insertarJuegoRequest(_EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarJuegoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarJuegoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oponente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int unidadesDesplegadas;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int unidadesSobrevivientes;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int unidadesDestruidas;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool gano;
        
        public insertarJuegoRequestBody() {
        }
        
        public insertarJuegoRequestBody(string nickname, string oponente, int unidadesDesplegadas, int unidadesSobrevivientes, int unidadesDestruidas, bool gano) {
            this.nickname = nickname;
            this.oponente = oponente;
            this.unidadesDesplegadas = unidadesDesplegadas;
            this.unidadesSobrevivientes = unidadesSobrevivientes;
            this.unidadesDestruidas = unidadesDestruidas;
            this.gano = gano;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarJuegoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarJuegoResponse", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarJuegoResponseBody Body;
        
        public insertarJuegoResponse() {
        }
        
        public insertarJuegoResponse(_EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarJuegoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertarJuegoResponseBody {
        
        public insertarJuegoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.eliminarUsuarioRequestBody Body;
        
        public eliminarUsuarioRequest() {
        }
        
        public eliminarUsuarioRequest(_EDD_Proyecto1_Cliente.ServidorIPEstatica.eliminarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        public eliminarUsuarioRequestBody() {
        }
        
        public eliminarUsuarioRequestBody(string nickname) {
            this.nickname = nickname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.eliminarUsuarioResponseBody Body;
        
        public eliminarUsuarioResponse() {
        }
        
        public eliminarUsuarioResponse(_EDD_Proyecto1_Cliente.ServidorIPEstatica.eliminarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class eliminarUsuarioResponseBody {
        
        public eliminarUsuarioResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerNicknameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerNickname", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNicknameRequestBody Body;
        
        public obtenerNicknameRequest() {
        }
        
        public obtenerNicknameRequest(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNicknameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerNicknameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        public obtenerNicknameRequestBody() {
        }
        
        public obtenerNicknameRequestBody(string nickname) {
            this.nickname = nickname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerNicknameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerNicknameResponse", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNicknameResponseBody Body;
        
        public obtenerNicknameResponse() {
        }
        
        public obtenerNicknameResponse(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNicknameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerNicknameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string obtenerNicknameResult;
        
        public obtenerNicknameResponseBody() {
        }
        
        public obtenerNicknameResponseBody(string obtenerNicknameResult) {
            this.obtenerNicknameResult = obtenerNicknameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerPassword", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerPasswordRequestBody Body;
        
        public obtenerPasswordRequest() {
        }
        
        public obtenerPasswordRequest(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        public obtenerPasswordRequestBody() {
        }
        
        public obtenerPasswordRequestBody(string nickname) {
            this.nickname = nickname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerPasswordResponseBody Body;
        
        public obtenerPasswordResponse() {
        }
        
        public obtenerPasswordResponse(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string obtenerPasswordResult;
        
        public obtenerPasswordResponseBody() {
        }
        
        public obtenerPasswordResponseBody(string obtenerPasswordResult) {
            this.obtenerPasswordResult = obtenerPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCorreoElectronicoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCorreoElectronico", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerCorreoElectronicoRequestBody Body;
        
        public obtenerCorreoElectronicoRequest() {
        }
        
        public obtenerCorreoElectronicoRequest(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerCorreoElectronicoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCorreoElectronicoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        public obtenerCorreoElectronicoRequestBody() {
        }
        
        public obtenerCorreoElectronicoRequestBody(string nickname) {
            this.nickname = nickname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCorreoElectronicoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCorreoElectronicoResponse", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerCorreoElectronicoResponseBody Body;
        
        public obtenerCorreoElectronicoResponse() {
        }
        
        public obtenerCorreoElectronicoResponse(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerCorreoElectronicoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCorreoElectronicoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string obtenerCorreoElectronicoResult;
        
        public obtenerCorreoElectronicoResponseBody() {
        }
        
        public obtenerCorreoElectronicoResponseBody(string obtenerCorreoElectronicoResult) {
            this.obtenerCorreoElectronicoResult = obtenerCorreoElectronicoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerConectadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerConectado", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerConectadoRequestBody Body;
        
        public obtenerConectadoRequest() {
        }
        
        public obtenerConectadoRequest(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerConectadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerConectadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        public obtenerConectadoRequestBody() {
        }
        
        public obtenerConectadoRequestBody(string nickname) {
            this.nickname = nickname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerConectadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerConectadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerConectadoResponseBody Body;
        
        public obtenerConectadoResponse() {
        }
        
        public obtenerConectadoResponse(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerConectadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerConectadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string obtenerConectadoResult;
        
        public obtenerConectadoResponseBody() {
        }
        
        public obtenerConectadoResponseBody(string obtenerConectadoResult) {
            this.obtenerConectadoResult = obtenerConectadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerJuegosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerJuegos", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerJuegosRequestBody Body;
        
        public obtenerJuegosRequest() {
        }
        
        public obtenerJuegosRequest(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerJuegosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerJuegosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        public obtenerJuegosRequestBody() {
        }
        
        public obtenerJuegosRequestBody(string nickname) {
            this.nickname = nickname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerJuegosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerJuegosResponse", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerJuegosResponseBody Body;
        
        public obtenerJuegosResponse() {
        }
        
        public obtenerJuegosResponse(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerJuegosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerJuegosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string obtenerJuegosResult;
        
        public obtenerJuegosResponseBody() {
        }
        
        public obtenerJuegosResponseBody(string obtenerJuegosResult) {
            this.obtenerJuegosResult = obtenerJuegosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarJuegosGanadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarJuegosGanados", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarJuegosGanadosRequestBody Body;
        
        public consultarJuegosGanadosRequest() {
        }
        
        public consultarJuegosGanadosRequest(_EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarJuegosGanadosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class consultarJuegosGanadosRequestBody {
        
        public consultarJuegosGanadosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarJuegosGanadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarJuegosGanadosResponse", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarJuegosGanadosResponseBody Body;
        
        public consultarJuegosGanadosResponse() {
        }
        
        public consultarJuegosGanadosResponse(_EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarJuegosGanadosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultarJuegosGanadosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string consultarJuegosGanadosResult;
        
        public consultarJuegosGanadosResponseBody() {
        }
        
        public consultarJuegosGanadosResponseBody(string consultarJuegosGanadosResult) {
            this.consultarJuegosGanadosResult = consultarJuegosGanadosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarPorcentajeUnidadesDestruidasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarPorcentajeUnidadesDestruidas", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarPorcentajeUnidadesDestruidasRequestBody Body;
        
        public consultarPorcentajeUnidadesDestruidasRequest() {
        }
        
        public consultarPorcentajeUnidadesDestruidasRequest(_EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarPorcentajeUnidadesDestruidasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class consultarPorcentajeUnidadesDestruidasRequestBody {
        
        public consultarPorcentajeUnidadesDestruidasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarPorcentajeUnidadesDestruidasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarPorcentajeUnidadesDestruidasResponse", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarPorcentajeUnidadesDestruidasResponseBody Body;
        
        public consultarPorcentajeUnidadesDestruidasResponse() {
        }
        
        public consultarPorcentajeUnidadesDestruidasResponse(_EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarPorcentajeUnidadesDestruidasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultarPorcentajeUnidadesDestruidasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string consultarPorcentajeUnidadesDestruidasResult;
        
        public consultarPorcentajeUnidadesDestruidasResponseBody() {
        }
        
        public consultarPorcentajeUnidadesDestruidasResponseBody(string consultarPorcentajeUnidadesDestruidasResult) {
            this.consultarPorcentajeUnidadesDestruidasResult = consultarPorcentajeUnidadesDestruidasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(_EDD_Proyecto1_Cliente.ServidorIPEstatica.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string nickname, string password) {
            this.nickname = nickname;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(_EDD_Proyecto1_Cliente.ServidorIPEstatica.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginResult;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(string loginResult) {
            this.loginResult = loginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class conectarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="conectar", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.conectarRequestBody Body;
        
        public conectarRequest() {
        }
        
        public conectarRequest(_EDD_Proyecto1_Cliente.ServidorIPEstatica.conectarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class conectarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        public conectarRequestBody() {
        }
        
        public conectarRequestBody(string nickname) {
            this.nickname = nickname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class conectarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="conectarResponse", Namespace="http://tempuri.org/", Order=0)]
        public _EDD_Proyecto1_Cliente.ServidorIPEstatica.conectarResponseBody Body;
        
        public conectarResponse() {
        }
        
        public conectarResponse(_EDD_Proyecto1_Cliente.ServidorIPEstatica.conectarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class conectarResponseBody {
        
        public conectarResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : _EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<_EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap>, _EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.HelloWorldResponse _EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap.HelloWorld(_EDD_Proyecto1_Cliente.ServidorIPEstatica.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.HelloWorldRequest inValue = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.HelloWorldRequest();
            inValue.Body = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.HelloWorldRequestBody();
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.HelloWorldResponse retVal = ((_EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarUsuarioResponse _EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap.insertarUsuario(_EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarUsuarioRequest request) {
            return base.Channel.insertarUsuario(request);
        }
        
        public string insertarUsuario(string nickname, string contraseña, string correoElectronico, bool conectado) {
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarUsuarioRequest inValue = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarUsuarioRequest();
            inValue.Body = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarUsuarioRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.contraseña = contraseña;
            inValue.Body.correoElectronico = correoElectronico;
            inValue.Body.conectado = conectado;
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarUsuarioResponse retVal = ((_EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap)(this)).insertarUsuario(inValue);
            return retVal.Body.insertarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarUsuariosResponse _EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap.graficarUsuarios(_EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarUsuariosRequest request) {
            return base.Channel.graficarUsuarios(request);
        }
        
        public string graficarUsuarios() {
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarUsuariosRequest inValue = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarUsuariosRequest();
            inValue.Body = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarUsuariosRequestBody();
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarUsuariosResponse retVal = ((_EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap)(this)).graficarUsuarios(inValue);
            return retVal.Body.graficarUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarEspejoResponse _EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap.graficarEspejo(_EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarEspejoRequest request) {
            return base.Channel.graficarEspejo(request);
        }
        
        public string graficarEspejo() {
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarEspejoRequest inValue = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarEspejoRequest();
            inValue.Body = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarEspejoRequestBody();
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.graficarEspejoResponse retVal = ((_EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap)(this)).graficarEspejo(inValue);
            return retVal.Body.graficarEspejoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerAlturaResponse _EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap.obtenerAltura(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerAlturaRequest request) {
            return base.Channel.obtenerAltura(request);
        }
        
        public string obtenerAltura() {
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerAlturaRequest inValue = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerAlturaRequest();
            inValue.Body = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerAlturaRequestBody();
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerAlturaResponse retVal = ((_EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap)(this)).obtenerAltura(inValue);
            return retVal.Body.obtenerAlturaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerHojasResponse _EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap.obtenerHojas(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerHojasRequest request) {
            return base.Channel.obtenerHojas(request);
        }
        
        public string obtenerHojas() {
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerHojasRequest inValue = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerHojasRequest();
            inValue.Body = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerHojasRequestBody();
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerHojasResponse retVal = ((_EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap)(this)).obtenerHojas(inValue);
            return retVal.Body.obtenerHojasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerRamasResponse _EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap.obtenerRamas(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerRamasRequest request) {
            return base.Channel.obtenerRamas(request);
        }
        
        public string obtenerRamas() {
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerRamasRequest inValue = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerRamasRequest();
            inValue.Body = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerRamasRequestBody();
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerRamasResponse retVal = ((_EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap)(this)).obtenerRamas(inValue);
            return retVal.Body.obtenerRamasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNivelesResponse _EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap.obtenerNiveles(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNivelesRequest request) {
            return base.Channel.obtenerNiveles(request);
        }
        
        public string obtenerNiveles() {
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNivelesRequest inValue = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNivelesRequest();
            inValue.Body = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNivelesRequestBody();
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNivelesResponse retVal = ((_EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap)(this)).obtenerNiveles(inValue);
            return retVal.Body.obtenerNivelesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarJuegoResponse _EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap.insertarJuego(_EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarJuegoRequest request) {
            return base.Channel.insertarJuego(request);
        }
        
        public void insertarJuego(string nickname, string oponente, int unidadesDesplegadas, int unidadesSobrevivientes, int unidadesDestruidas, bool gano) {
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarJuegoRequest inValue = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarJuegoRequest();
            inValue.Body = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarJuegoRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.oponente = oponente;
            inValue.Body.unidadesDesplegadas = unidadesDesplegadas;
            inValue.Body.unidadesSobrevivientes = unidadesSobrevivientes;
            inValue.Body.unidadesDestruidas = unidadesDestruidas;
            inValue.Body.gano = gano;
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.insertarJuegoResponse retVal = ((_EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap)(this)).insertarJuego(inValue);
        }
        
        public void limpiar() {
            base.Channel.limpiar();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.eliminarUsuarioResponse _EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap.eliminarUsuario(_EDD_Proyecto1_Cliente.ServidorIPEstatica.eliminarUsuarioRequest request) {
            return base.Channel.eliminarUsuario(request);
        }
        
        public void eliminarUsuario(string nickname) {
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.eliminarUsuarioRequest inValue = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.eliminarUsuarioRequest();
            inValue.Body = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.eliminarUsuarioRequestBody();
            inValue.Body.nickname = nickname;
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.eliminarUsuarioResponse retVal = ((_EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap)(this)).eliminarUsuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNicknameResponse _EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap.obtenerNickname(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNicknameRequest request) {
            return base.Channel.obtenerNickname(request);
        }
        
        public string obtenerNickname(string nickname) {
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNicknameRequest inValue = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNicknameRequest();
            inValue.Body = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNicknameRequestBody();
            inValue.Body.nickname = nickname;
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerNicknameResponse retVal = ((_EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap)(this)).obtenerNickname(inValue);
            return retVal.Body.obtenerNicknameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerPasswordResponse _EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap.obtenerPassword(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerPasswordRequest request) {
            return base.Channel.obtenerPassword(request);
        }
        
        public string obtenerPassword(string nickname) {
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerPasswordRequest inValue = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerPasswordRequest();
            inValue.Body = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerPasswordRequestBody();
            inValue.Body.nickname = nickname;
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerPasswordResponse retVal = ((_EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap)(this)).obtenerPassword(inValue);
            return retVal.Body.obtenerPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerCorreoElectronicoResponse _EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap.obtenerCorreoElectronico(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerCorreoElectronicoRequest request) {
            return base.Channel.obtenerCorreoElectronico(request);
        }
        
        public string obtenerCorreoElectronico(string nickname) {
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerCorreoElectronicoRequest inValue = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerCorreoElectronicoRequest();
            inValue.Body = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerCorreoElectronicoRequestBody();
            inValue.Body.nickname = nickname;
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerCorreoElectronicoResponse retVal = ((_EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap)(this)).obtenerCorreoElectronico(inValue);
            return retVal.Body.obtenerCorreoElectronicoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerConectadoResponse _EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap.obtenerConectado(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerConectadoRequest request) {
            return base.Channel.obtenerConectado(request);
        }
        
        public string obtenerConectado(string nickname) {
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerConectadoRequest inValue = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerConectadoRequest();
            inValue.Body = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerConectadoRequestBody();
            inValue.Body.nickname = nickname;
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerConectadoResponse retVal = ((_EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap)(this)).obtenerConectado(inValue);
            return retVal.Body.obtenerConectadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerJuegosResponse _EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap.obtenerJuegos(_EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerJuegosRequest request) {
            return base.Channel.obtenerJuegos(request);
        }
        
        public string obtenerJuegos(string nickname) {
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerJuegosRequest inValue = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerJuegosRequest();
            inValue.Body = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerJuegosRequestBody();
            inValue.Body.nickname = nickname;
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.obtenerJuegosResponse retVal = ((_EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap)(this)).obtenerJuegos(inValue);
            return retVal.Body.obtenerJuegosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarJuegosGanadosResponse _EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap.consultarJuegosGanados(_EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarJuegosGanadosRequest request) {
            return base.Channel.consultarJuegosGanados(request);
        }
        
        public string consultarJuegosGanados() {
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarJuegosGanadosRequest inValue = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarJuegosGanadosRequest();
            inValue.Body = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarJuegosGanadosRequestBody();
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarJuegosGanadosResponse retVal = ((_EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap)(this)).consultarJuegosGanados(inValue);
            return retVal.Body.consultarJuegosGanadosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarPorcentajeUnidadesDestruidasResponse _EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap.consultarPorcentajeUnidadesDestruidas(_EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarPorcentajeUnidadesDestruidasRequest request) {
            return base.Channel.consultarPorcentajeUnidadesDestruidas(request);
        }
        
        public string consultarPorcentajeUnidadesDestruidas() {
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarPorcentajeUnidadesDestruidasRequest inValue = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarPorcentajeUnidadesDestruidasRequest();
            inValue.Body = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarPorcentajeUnidadesDestruidasRequestBody();
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.consultarPorcentajeUnidadesDestruidasResponse retVal = ((_EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap)(this)).consultarPorcentajeUnidadesDestruidas(inValue);
            return retVal.Body.consultarPorcentajeUnidadesDestruidasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.loginResponse _EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap.login(_EDD_Proyecto1_Cliente.ServidorIPEstatica.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public string login(string nickname, string password) {
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.loginRequest inValue = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.loginRequest();
            inValue.Body = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.loginRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.password = password;
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.loginResponse retVal = ((_EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap)(this)).login(inValue);
            return retVal.Body.loginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _EDD_Proyecto1_Cliente.ServidorIPEstatica.conectarResponse _EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap.conectar(_EDD_Proyecto1_Cliente.ServidorIPEstatica.conectarRequest request) {
            return base.Channel.conectar(request);
        }
        
        public void conectar(string nickname) {
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.conectarRequest inValue = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.conectarRequest();
            inValue.Body = new _EDD_Proyecto1_Cliente.ServidorIPEstatica.conectarRequestBody();
            inValue.Body.nickname = nickname;
            _EDD_Proyecto1_Cliente.ServidorIPEstatica.conectarResponse retVal = ((_EDD_Proyecto1_Cliente.ServidorIPEstatica.WebService1Soap)(this)).conectar(inValue);
        }
    }
}
